# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8abeb19580edab8410772c68e7d5875b6a985a228b7d188e6d7c78d66e38a682a4f1770570fc472bdf740608b9d09fd93d531295f48c4a15baa2df36cee92b0

test:
  secret_key_base: d7cd26f732bf0e057bdc0af93595811fe8d91ecfcce192e5c2658b5bd840e1f6d51f070f16f08511d5ff01ba864b77580f8b9534c5a567686e3c2018840b09c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
